services:
  db:
    env_file: .env
    image: mariadb:latest
    container_name: gestion_recette
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"

  app:
    env_file: .env
    image: fatoumacisse99/api-gestion-recette:latest
    container_name: recette-api
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    ports:
      - "3010:3010"
    depends_on:
      - db
volumes:
  db-data:
